 version: "3.7"
 services:

   node1:
     container_name: Node1
     build: Node1/.

   node2:
     container_name: Node2
     build: Node2/.

   node3:
     container_name: Node3
     build: Node3/.
