version: '3.7'
services:
  mongo:
    image: mongo:4.2.5
    environment:
      -MONGO_INITDB_ROOT_USERNAME: 486mongo
      -MONGO_INITDB_ROOT_PASSWORD: 2P54wLApQYGslIrG
    ports:
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db
  server_leader:
    build: .
    container_name: node
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - "5000:5000"
      # - "5001:5000"
      # - "5002:5000"
  server_two:
    build: .
    container_name: node1
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - "5001:5000"
  server_three:
    build: .
    container_name: node2
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - "5002:5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server_leader
    ports:
      - "4000:4000"
volumes:
  mongo_vol: