version: '3.7'
services:
  mongo:
    image: mongo:4.2.5
    environment:
      -MONGO_INITDB_ROOT_USERNAME: 486mongo
      -MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db
  app:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - "5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "4000:4000"
volumes:
  mongo_vol: