# This is a sample docker-compose file, Please follow the naming convention for the service and container name, all node
# names must begin with "Node" followed by their sequence number. For a three node cluster your service/container names
# should be Node1, Node2 and Node3 as shown below(for service names they will be lowercase). You can add additional
# parameters and configurations as required by your implementation.


version: "3.7"
services:
   node1:
     environment: 
       - NAME=Node1
     container_name: Node1
     build: Node/.
     volumes: 
       - data-persist:/app

   node2:
     environment: 
       - NAME=Node2
     container_name: Node2
     build: Node/.
     volumes: 
       - data-persist-2:/app

   node3:
     environment: 
       - NAME=Node3
     container_name: Node3
     build: Node/.
     volumes: 
       - data-persist-3:/app

   node4:
     environment: 
       - NAME=Node4
     container_name: Node4
     build: Node/.
     volumes: 
       - data-persist-4:/app

   node5:
     environment: 
       - NAME=Node5
     container_name: Node5
     build: Node/.
     volumes: 
       - data-persist-5:/app

   #Do not change the part below
   controller:
       container_name: Controller
       build: Controller/.
       stdin_open: true
       
volumes:
  data-persist:
    external: true
  data-persist-2:
    external: true
  data-persist-3:
    external: true
  data-persist-4:
    external: true
  data-persist-5:
    external: true







