# This is a sample docker-compose file, Please follow the naming convention for the service and container name, all node
# names must begin with "Node" followed by their sequence number. For a three node cluster your service/container names
# should be Node1, Node2 and Node3 as shown below(for service names they will be lowercase). You can add additional
# parameters and configurations as required by your implementation.


version: "3.7"
services:
   node1:
     environment: 
       - NAME=Node1
     container_name: Node1
     build: Node/.

   node2:
     environment: 
       - NAME=Node2
     container_name: Node2
     build: Node/.

  #  node3:
  #      container_name: Node3
  #      build: Node/.

   #Do not change the part below
   controller:
       container_name: Controller
       build: Controller/.
       stdin_open: true









